### ISSUE TITLE
#Issue1

### ISSUE THREAD

**Issue by graccy4eva** [SomuahAsante/next_level#1]
@SomuahAsante please state the issues to be resolved here

**Comment by SomuahAsante** [comment]
1. please with the Jupiter notebook code I would like to know if the code is submittable and possible areas to look at if it is not
2. with the flask app, it isn't working at all.

**Comment by graccy4eva** [comment]
Ok.

**Comment by SomuahAsante** [comment]
Thank you

**Comment by SomuahAsante** [comment]
Dr Grace  please I cannot see the issues comment.
I am really sorry for the stress. Thank you.
